### ISSUE TITLE
每次的交易都是独立的，会导致玩家买错东西并占用服务器的CPU资源

### ISSUE THREAD

**Issue by ahdg6** [IzzelAliz/AmberShop#14]
当非商店主人购买出售一件物品时，先后点不同的两个商店箱子，后者不会覆盖前者，会创建两个独立的交易会话，当玩家第一次是点错的时候，点第二个商店，输入购买数量响应的是第一次点击的商店
而当恶意玩家将商店一排排点过去，将会对服务器的TPS造成较为明显的影响

**Comment by IzzelAliz** [comment]
Fixed in 1fb2765578cc1ae026b439536b54e574e36bfa0c

**Comment by ahdg6** [comment]
感谢作者修复了这个，但若重复上述行为扔会有 [给你输入的时间已经过了] 的信息出现在第二个商店信息输出之后，这可能将会造成不必要的误会
![EYC$QHL@TSO{NZI{)E2 4Z2](https://user-images.githubusercontent.com/36436808/62617290-1c95ba00-b944-11e9-9f18-7e874c2dbb47.png)

**Comment by IzzelAliz** [comment]
这个信息不是理应出现的吗 ...

**Comment by ahdg6** [comment]
这个消息出现是在点击第二个商店信息出来之后，也就是会造成这个信息是指目前交易会话的误解
