### ISSUE TITLE
displayItem bug

### ISSUE THREAD

**Issue by bigenergy** [IzzelAliz/AmberShop#15]
If displayItem=true
ring of magnetism (botania mod) attracts objects over the chest to the player

![image](https://user-images.githubusercontent.com/17977139/61581457-ea542200-ab26-11e9-91ce-aaceab441df8.png)

**Comment by IzzelAliz** [comment]
The displayed item do not exists in server actually. I'm not sure if this fake ring item does affect objects in server or it is just a client effect.

 Anyway, I will add a blacklist function in next release using EpicBanItem amd.you can ban displaying this.
