### ISSUE TITLE
bug?特性?

### ISSUE THREAD

**Issue by axin0452** [IzzelAliz/AmberShop#16]
当服务器有mod被删除时. 该mod的方块又在商店里售卖..那么那个箱子和附近的一些箱子将无法使用.,此时你也无法再创建新的箱子商店了..但是已经创建好的部分箱子商店是可以正常使用的

**Comment by axin0452** [comment]
包括你使用指令的方式来创建 as create|c <price> 也是不可以创建的 输入这个指令后台也没有报错..

**Comment by IzzelAliz** [comment]
删除mod为未定义行为，我建议服主规划好服务器不要删除mod。
考虑在下一个版本修复
