### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by bigenergy** [IzzelAliz/AmberShop#2]
https://hastebin.com/qebowuzabi.rb
https://hastebin.com/jebulacuqo.md

**Comment by bigenergy** [comment]
+ when creating a store does not create a table

**Comment by IzzelAliz** [comment]
It is a mixin failure. Cannot reproduce it on spongeforge 2838-7.1.7-RC3784

**Comment by IzzelAliz** [comment]
You may put AmberShop.jar in the /mods folder, not the /mods/plugins folder, because it is a mixin plugin.

**Comment by bigenergy** [comment]
Thanks, it's worked!
