### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by axin0452** [IzzelAliz/AmberShop#21]
**Describe the bug**
当我把插件升级到1.1.0版本之后 玩家出现了无法修改价格的错误显示

**To Reproduce**
当玩家放置一个箱子 然后输入-1 的价格进行收购  然后再次点击箱子 点击更改设置价格,然后输入新的价格就会出现下图提示
https://s2.ax1x.com/2019/08/12/mpEcwj.png

**Environment:**
spongeforge-1.12.2-2825-7.1.6-RC3755
AmberShop-1.1.0-all.jar

**Stacktrace/Crash report**
后台无报错

**Comment by IzzelAliz** [comment]
给 ambershop.user.query 权限
