### ISSUE TITLE
Can not compatible with Ironchest mod

### ISSUE THREAD

**Issue by zsn741656478** [IzzelAliz/AmberShop#22]
**Describe the bug**
https://i.loli.net/2019/08/13/b7ocBr1dAhOPEmZ.png

**To Reproduce**
Use iron chest and create a shop.

**Environment:**
 - Sponge version: spongeforge-1.12.2-7.1.6
 - AmberShop version 1.1.1

**Stacktrace/Crash report**
https://i.loli.net/2019/08/13/b7ocBr1dAhOPEmZ.png

**Comment by IzzelAliz** [comment]
修不了
