### ISSUE TITLE
Language Missing

### ISSUE THREAD

**Issue by Spontini** [IzzelAliz/AmberShop#24]
![image](https://user-images.githubusercontent.com/35429381/64066755-6a8d9d00-cc26-11e9-9b9e-6cd8390f1fa5.png)

**Comment by IzzelAliz** [comment]
Manually add this to locale_xx_xx.conf file.
```
sold-after-tax = "&aTransaction success. After-tax amount is {0}."
```
I'm sorry for missing this.
