### ISSUE TITLE
alias confliction

### ISSUE THREAD

**Issue by KhaozFrost** [IzzelAliz/AmberShop#26]
**Describe the bug**
due to the plugin using /as it conflicts with adamanteshields /as i command
tried forcing it in the sponge config so that adamanteshield prioritizes is but no luck.. this is a big problem for anyone that requires their server to use block loggers.

**To Reproduce**
Steps to reproduce the bug.

**Environment:**
 - Sponge version: [e.g. spongevanilla-1.12.2-7.1.6]
 - AmberShop version [e.g. 1.0.4]

**Stacktrace/Crash report**
You may put it on https://paste.ubuntu.com if possible.

**Comment by IzzelAliz** [comment]
`/ambershop` is also ok.
