### ISSUE TITLE
[问题]无法正常使用AmberShop

### ISSUE THREAD

**Issue by SakuraWuhen** [IzzelAliz/AmberShop#33]
**Environment:**
 - Sponge version: [spongeforge-1.12.2-2838-7.1.8]
 - AmberShop version [1.1.6]
 - LuckPerms-Sponge-5.0.130
 - latch-0.5.1-S7.1.0
 - EconomyLite-7.1.0-2.15.1

**Describe the bug**
很抱歉，我没有报错，也不清楚这是否算是一个bug，但我的确遇到了问题
问题的核心在于：
我使用了正确的版本正确的步骤，仍无法使用AmberShop
左键箱子没有反应，在箱子内放入物品并输入指令永远提示"你需要指向一个方块"
![QQ截图20200416122806](https://user-images.githubusercontent.com/45621850/79414681-d4a05a00-7fdd-11ea-908b-5a26dc45160f.png)
*插件是有成功载入的，指令列表都有出来

**To Reproduce**
我已确认有完整的翻过MCBBS的帖子与WIKI，并按文中所述的步骤尝试，但就是没有任何反应。
为此，我还装载了文中提到的锁箱、经济、LP权限(并确定插件的九个权限皆已给自己)
自己折腾了半天后没有结果，加群也并没有人批，只能来此请求您的帮助
如果是我漏了哪个步骤，我为此感到抱歉

**Comment by SakuraWuhen** [comment]
@IzzelAliz 我确实是输入了价格的，我输入的是 /as create 10
输入价格后才会出现“你没有一指向一个方块”
箱子里我有放一组草方块，这些应该都是按wiki中的步骤所做的，但都没有用

**Comment by SakuraWuhen** [comment]
我刚才做了一次排查，将除spongeforge外的模组移除，随后进行和上面一样的操作，插件成功创建了牌子商店，随后将被移除的模组装回，插件失效，指令创建牌子商店仍提示”你没有指向一个方块“
* 由此可以确定问题出在模组
您对此有什么头绪吗？进行更进一步的对比排查会花费很多的时间，我可以试试找到出问题的模组

**Comment by SakuraWuhen** [comment]
今天运气真好，第二轮排查就找到了出问题的模组 —— VanillaFix
这是一个非常棒的优化模组，但它的确对minecraft做了大量侵入式修改
https://www.mcmod.cn/class/1223.html
您可以在CurseForge找到完整的特性列表，还劳烦看看是哪项特性导致了这个问题，谢谢

**Comment by IzzelAliz** [comment]
能发一个 vanillafix 的版本号吗，此前用了这么久并没有其他用户反馈有这种兼容问题

**Comment by SakuraWuhen** [comment]
我用的版本是 VanillaFix-1.1.1-138
CurseForge上的版本不全，还请去github看发行的版本，信息也更完善一些
并且我测试的时候，服务端删除了VanillaFix，但客户端本地仍载入，可以排除一些本地功能的嫌疑
辛苦了

**Comment by IzzelAliz** [comment]
vanillafix 不是装在服务端的

**Comment by SakuraWuhen** [comment]
！！原来是这样吗
那真是抱歉，是我的问题，感谢帮助
