### ISSUE TITLE
Console spammed by sponge issue with your pl

### ISSUE THREAD

**Issue by pjindras** [IzzelAliz/AmberShop#37]
**Describe the bug**
My console is instantly spammed by sponge with some warn issues of amber shops 

**To Reproduce**
Idk, just run it.

**Environment:**
 - Sponge version: 1.12.2-2838-7.2.3
 - AmberShop version 1.1.6

log:
https://pastebin.com/y8J0Qtsz

**Comment by IzzelAliz** [comment]
Duplicate of #19.
