### ISSUE TITLE
[Feature] Shop player limits

### ISSUE THREAD

**Issue by bigenergy** [IzzelAliz/AmberShop#4]
This plugin lacks one more functionality, the limit of stores per player group.
This option was in QuickShop bukkit.

Example:
- ambershop.limit.10 - limit the player with this permission to create no more than 10 stores

**Comment by IzzelAliz** [comment]
Add in next release.

**Comment by IzzelAliz** [comment]
Add a new config `shopSettings.maxShops` for default limit.
Use `lp user|group xxx meta set ambershop.max-shop <amount>` for per player limit.
Set to -1 to disable limit.
