### ISSUE TITLE
Missing commands.create.fail.no-ItemName when using the command

### ISSUE THREAD

**Issue by TheRealDadbeard** [IzzelAliz/AmberShop#6]
Getting this error in the chatbox when using the command to create a new shop

**Comment by IzzelAliz** [comment]
You can add this manually. Will fix in next release.

**Comment by TheRealDadbeard** [comment]
Like how? I don't know what this error is telling me. If I could fix this for my self I would.

**Comment by IzzelAliz** [comment]
Add this in locale.conf, if you are clever enough you can guess how.
