### ISSUE TITLE
Anyone can open the chest and take items out

### ISSUE THREAD

**Issue by TheRealDadbeard** [IzzelAliz/AmberShop#7]
Title. The chest just opens right up and you can take the stuff

**Comment by IzzelAliz** [comment]
Other plugins like Latch can do this and I don'twant to write another latch.
If there are more requests, I'll consider this.

**Comment by zsn741656478** [comment]
> Title. The chest just opens right up and you can take the stuff

You can enable the GP or Latch "auto lock on placement" feature.

**Comment by TheRealDadbeard** [comment]
does latch play nicely with griefprevention? serialkey should do the same but being newer
